name: communitydownloader
description: Community Image Downloader

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.9.4+22

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  
  aes_crypt:
  # animated_widgets:
  # animations:
  async:
  # auto_animated: any
  cached_network_image:
  # carousel_slider:
  # charts_flutter:
  # circular_check_box: ^1.0.1
  convert:
  country_pickers:
  crypto:
  csslib:
  device_info:
  # dio:
  # division:
  # draggable_scrollbar:
  dynamic_theme: ^1.0.1
  # encrypt: ^4.0.1
  expandable:
  ext_storage:
  ffi:
  flutter_ffmpeg: ^0.2.10
  file_picker:
  firebase_analytics:
  # firebase_crashlytics:
  flare_dart:
  flare_flutter: ^1.8.3
  flutter_archive:
  flutter_colorpicker:
  # flutter_downloader:
  # flutter_mobx:
  # flutter_reorderable_list:
  # flutter_native_image:
  # flutter_inner_drawer: "^0.5.7+2"
  opencv:
    path: flutter_opencv
  flutter_mailer:
  flutter_secure_storage:
  flutter_speed_dial:
  flutter_staggered_animations: "^0.1.2"
  flutter_svg:
  fluttertoast: ^6.0.1
  # gradient_widgets:
  # html: 0.14.0+3
  html_unescape:
  http:
  in_app_purchase:
  intl: ^0.16.0
  # image:
  kdtree:
  # lottie:
  material_design_icons_flutter:
  mdi:
  open_file:
  path:
  path_provider:
  permission_handler:
  photo_view:
  # pimp_my_button: ^1.0.0
  shell:
  provider:
  receive_sharing_intent:
  shared_preferences:
  sqflite:
  synchronized:
  # system_alert_window:
  #   path: ./alertwindow
  tuple:
  url_launcher:
  uuid:
  # vibration: ^1.4.0
  # flutter_webview_plugin:
  webview_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
    - assets/images/logo.png
  
    - assets/flare/switch_daytime.flr
    - assets/flare/Loading2.flr

    # - assets/icons/pixiv.ico
    
    - assets/locale/en.json
    - assets/locale/ko.json
    # - assets/locale/ja.json
    # - assets/locale/zh.json
    # - assets/locale/zh_Hant.json
    # - assets/locale/zh_Hans.json
    # - assets/locale/it.json
    # - assets/locale/eo.json

    # - assets/libviolet/arm64-v8a/libviolet.so
    # - assets/libviolet/armeabi-v7a/libviolet.so
    # - assets/libviolet/x86/libviolet.so
    # - assets/libviolet/x86_64/libviolet.so

    - assets/youtube-dl/youtube-dl-debug.zip
    - assets/youtube-dl/youtube-dl-release-aarch64.zip
    - assets/youtube-dl/youtube-dl-release-arm.zip


    # - assets/python/x86/libpython3.so
    # - assets/python/x86/libpython3.8.so
    # - assets/python/x86/libpython3.8.so.1.0
    # - assets/python/x86/python
    # - assets/python/x86/python3


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  # fonts:
  #   - family: SF-Pro-Text-Regular
  #     fonts:
  #       - asset: assets/SF-Pro-Text-Regular.otf

  #   - family: SF-Pro-Text-Bold
  #     fonts:
  #       - asset: assets/SF-Pro-Text-Bold.otf

  #   - family: Calibre-Semibold
  #     fonts:
  #       - asset: assets/Calibre-Semibold.otf

  #   - family: CustomIcons
  #     fonts:
  #       - asset: assets/custom_icons.ttf
   